### ISSUE TITLE
Command Execute Error

### ISSUE THREAD

**Issue by mroa04** [SnoopJesus420/MAQ-Attaq#1]
https://github.com/SnoopJesus420/MAQ-Attaq/blob/1c92254f541a505d53789c89e119d5df560304e9/maq-attaq.py#L86

Missing "relay" before "-target" . Otherwise you get the error 

Error running command: certipy -target http://X.X.X.X -template Machine
Certipy v4.8.2 - by Oliver Lyak (ly4k)

usage: certipy [-v] [-h]
               {account,auth,ca,cert,find,forge,ptt,relay,req,shadow,template}
               ...
certipy: error: argument action: invalid choice: 'http://X.X.X.X' (choose from 'account', 'auth', 'ca', 'cert', 'find', 'forge', 'ptt', 'relay', 'req', 'shadow', 'template')

**Comment by SnoopJesus420** [comment]
Added the relay command switch on line 86. Closing.
